### ISSUE TITLE
code question

### ISSUE THREAD

**Issue by huanghlin** [jeonghwaYoo/sednn_modify#1]
Hello, I have one questions about the  code
     In main.py , line261, 
 s *= np.sqrt((np.hamming(n_window)**2).sum())
Can you  explain why s is multiplied by  np.sqrt((np.hamming(n_window)**2).sum()) ?
I use python to find the value of np.sqrt((np.hamming(n_window)**2).sum()) is 10.067.
I would like to know the reason for this writing, thank you.

**Comment by jeongHwarr** [comment]
@huanghlin Sorry for the late reply. 
It's just to compensate for the amplitude of the audio, and it doesn't matter much.
